export const AVAILABLE_PREFERENCES = {
  categories: [
    "Fashion",
    "Home",
    "Electronics",
    "Beauty",
    "Sports",
    "Books",
    "Toys",
    "Food & Grocery",
  ],
  dietary: [
    "Vegetarian",
    "Vegan",
    "Gluten-free",
    "Organic",
    "Keto",
    "Dairy-free",
  ],
  events: [
    "Christmas",
    "Boxing Day",
    "Black Friday",
    "Easter",
    "Summer Sale",
    "New Year",
    "Mother's Day",
    "Father's Day",
  ],
  style: [
    "Minimalist",
    "Casual",
    "Formal",
    "Sporty",
    "Vintage",
    "Boho",
    "Modern",
    "Classic",
  ],
  brands: [
    "Nike",
    "Adidas",
    "Puma",
    "Tommy Hilfiger",
    "Calvin Klein",
    "Gucci",
    "Zara",
    "H&M",
  ],
};
